/* =========================================================
   projects-data.js
   Single source of truth for every project on the site.
   Add a new project = add one object to PROJECTS. No new
   HTML file needed — project.html renders any slug on demand.
   ========================================================= */

const CATEGORIES = [
  { id: "aeronautics", label: "Aeronautics & Aerospace" },
  { id: "design-cad", label: "Design & CAD" },
  { id: "fabrication", label: "Fabrication & Manufacturing" },
  { id: "competition", label: "Competition Teams" },
  { id: "research", label: "Coursework & Research" },
  { id: "lego", label: "LEGO Creations" },
  { id: "personal", label: "Personal Projects" },
];

/* Tags are cross-cutting labels. A project can carry several, so a build
   can be both "Star Wars" and "Mini-Build". The Projects page turns every
   tag in use into a clickable filter. Order here = display order. */
const TAGS = [
  { id: "lego", label: "LEGO" },
  { id: "technic", label: "Technic" },
  { id: "star-wars", label: "Star Wars" },
  { id: "spacecraft", label: "Spacecraft" },
  { id: "aircraft", label: "Aircraft" },
  { id: "aviation", label: "Aviation" },
  { id: "warship", label: "Ships" },
  { id: "vehicle", label: "Vehicles" },
  { id: "mini-build", label: "Mini-Build" },
  { id: "diorama", label: "Diorama" },
  { id: "moc", label: "Original Design" },
  { id: "cad", label: "CAD" },
  { id: "robotics", label: "Robotics" },
  { id: "research", label: "Research" },
  { id: "fabrication", label: "Fabrication" },
  { id: "woodworking", label: "Woodworking" },
];

const PROJECTS = [
  {
    slug: "venator-star-destroyer",
    title: "Venator-Class Star Destroyer",
    category: "lego",
    tags: ["lego", "star-wars", "spacecraft", "moc"],
    date: "2026",
    summary:
      "A large scratch-built Venator-class Star Destroyer — the Republic attack cruiser from the Clone Wars — in light grey with red command stripes.",
    description: [
      "A scratch-built LEGO model of the Venator-class Star Destroyer, the Republic's main capital ship through the Clone Wars. It's an original build rather than a set: the wedge hull, the twin dorsal command towers, and the long red spine stripes are all worked out in brick from reference images.",
      "Add your own notes here — rough length in studs, how you handled the pointed bow and the dorsal hangar spine, part count, and how long it took. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Scale Modeling", "MOC Design"],
    images: [
      { src: "assets/images/venator-star-destroyer/venator-1.jpg", caption: "Full side profile" },
      { src: "assets/images/venator-star-destroyer/venator-2.jpg", caption: "Bow, three-quarter view" },
      { src: "assets/images/venator-star-destroyer/venator-3.jpg", caption: "Dorsal spine and command towers" },
      { src: "assets/images/venator-star-destroyer/venator-4.jpg", caption: "On its display stand" },
    ],
    references: [
      {
        src: "assets/images/venator-star-destroyer/reference-venator.jpg",
        caption: "Reference — Venator-class Star Destroyer",
      },
    ],
    links: {},
    featured: true,
    needsDetail: true,
  },
  {
    slug: "technic-experimental-floatplane",
    title: "Experimental Floatplane — LEGO Technic",
    category: "lego",
    tags: ["lego", "technic", "aircraft", "aviation", "moc"],
    date: "2026",
    summary:
      "A scratch-built LEGO Technic bush plane in the spirit of a Piper Cub — currently on floats, with working ailerons, flaps, and elevator.",
    description: [
      "A scratch-built LEGO Technic floatplane. It isn't a replica of any one airplane — it's an experimental design of my own, laid out in the spirit of a Piper Cub and the Cub-style bush planes that came after it: a high strut-braced wing, a squared-off fuselage, and a big slow-turning prop up front. Right now it's rigged as a floatplane, sitting on a pair of floats instead of tires.",
      "The goal was working controls, not just the right silhouette. The ailerons, flaps, and elevator all actually move. That drove the whole internal layout — the wing had to be a frame with room to run linkages out to the hinge lines rather than a solid panel, and the elevator run had to travel the length of the fuselage to the tail without fouling anything. Flaps and ailerons share the same trailing edge, so the span is split and each surface is hinged independently, with enough clearance that neither binds against the other at full deflection.",
      "The interesting problems were all about load paths and slack. Struts make the high wing easy — that's why the real Cub uses them — but floats put the airplane's whole weight into two narrow mounts hanging well below the fuselage, and the model is top-heavy on them, so the float pylons carry more bracing than they look like they need. The controls were harder. Technic geometry has almost no slack in it: a linkage that swings freely at neutral will bind at full travel if a hinge sits a stud off. Most of the iteration in the build went into hinge placement, getting each surface to reach full deflection without jamming.",
    ],
    tools: ["LEGO Technic", "Mechanical Linkages", "Scale Modeling", "General Aviation"],
    images: [
      "assets/images/technic-aircraft/lego-technic-aircraft-1.jpg",
      { src: "assets/images/technic-aircraft/floatplane-2.jpg", caption: "On floats, three-quarter view" },
      { src: "assets/images/technic-aircraft/floatplane-3.jpg", caption: "Head-on, showing the float pylons" },
      { src: "assets/images/technic-aircraft/floatplane-4.jpg", caption: "Rear three-quarter view" },
      { src: "assets/images/technic-aircraft/floatplane-5.jpg", caption: "Head-on with wheeled gear" },
      { src: "assets/images/technic-aircraft/floatplane-6.jpg", caption: "Side view with wheeled gear" },
      { src: "assets/images/technic-aircraft/floatplane-7.jpg", caption: "Three-quarter view with wheeled gear" },
    ],
    links: {},
    featured: true,
  },
  {
    slug: "lego-mini-builds",
    title: "LEGO Mini-Builds",
    category: "lego",
    tags: ["lego", "mini-build", "moc"],
    date: "2026",
    summary:
      "A run of micro-scale builds — a Shuttle Carrier 747, an oared galley, a formula car, an ocean liner — each made from as few bricks as the shape will tolerate.",
    description: [
      "I keep coming back to mini-builds because of the constraint. A big set hands you the exact part for every curve; a mini-build gives you a handful of ordinary bricks and asks you to suggest the whole thing anyway. Working out which few details actually carry the identity of an object — and which ones you can throw away without anyone noticing — is the part that excites me. It's the most purely creative building I do, and the small ones take the most thinking per brick.",
      "At this scale you can't reproduce a shape, only imply it, so the job becomes choosing what to keep. An ocean liner lives in the spacing and rake of its funnels; a formula car lives in the wings overhanging front and rear and the wheels standing outside the bodywork; a galley lives in the oars and the ram. Get those handful of cues right and the eye supplies everything else on its own.",
      "The Shuttle Carrier is the one I'm happiest with, and it's photographed twice for a reason: once with the orbiter mated on the 747's spine the way NASA ferried the shuttles cross-country, and once with the two pulled apart so each airframe reads on its own. They're a single build in two pieces. The problem to solve was the mount — it had to hold the shuttle firmly enough to pick the whole stack up by the 747, and still let the orbiter lift off cleanly without taking a row of the carrier's fuselage with it.",
    ],
    tools: ["LEGO", "Micro-Scale Design", "Parts Efficiency"],
    images: [
      "assets/images/mini-builds/shuttle-carrier-mated.jpg",
      "assets/images/mini-builds/shuttle-carrier-separated.jpg",
      "assets/images/mini-builds/ocean-liner.jpg",
      "assets/images/mini-builds/galley.jpg",
      "assets/images/mini-builds/formula-car.jpg",
    ],
    links: {},
    featured: false,
  },
  {
    slug: "at-at-hoth-assault",
    title: "AT-AT Hoth Assault Diorama",
    category: "lego",
    tags: ["lego", "star-wars", "diorama", "technic", "moc"],
    summary:
      "A Battle of Hoth diorama built around an AT-AT walker, with a geared Technic mechanism housed in the backdrop.",
    description: [
      "A diorama of the AT-AT assault on Echo Base from The Empire Strikes Back. A grey AT-AT walker stands on a white snow base framed by a tall backdrop, with snowspeeders and trench details in the foreground.",
      "The back of the backdrop hides a Technic gear train that drives the scene. Add your notes here: what the mechanism moves, how it is powered, and what was hardest to get working. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "LEGO Technic", "Gear Trains", "Diorama Design"],
    images: [
      { src: "assets/images/at-at-hoth-assault/hoth-2.jpg", caption: "AT-AT advancing across the snow base" },
      { src: "assets/images/at-at-hoth-assault/hoth-1.jpg", caption: "Front view with the backdrop" },
      { src: "assets/images/at-at-hoth-assault/hoth-3.jpg", caption: "Side view of the walker and trench" },
      { src: "assets/images/at-at-hoth-assault/hoth-4.jpg", caption: "Rear view showing the gear mechanism" },
    ],
    references: [
      { src: "assets/images/at-at-hoth-assault/reference-hoth.jpg", caption: "Reference: AT-AT assault on Hoth" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "lambda-shuttle-landing",
    title: "Lambda Shuttle Landing Diorama",
    category: "lego",
    tags: ["lego", "star-wars", "spacecraft", "diorama", "moc"],
    summary:
      "An Imperial Lambda-class shuttle touching down on a jungle landing pad, with folding wings and landing gear on a Technic frame.",
    description: [
      "A diorama of an Imperial Lambda-class shuttle landing in a jungle clearing, with palm trees, foliage and water around a raised landing pad. The shuttle is held up on a black Technic frame and its wings are shown both raised and folded.",
      "Add your notes here: how the wing fold works, whether the landing motion is mechanical, and how the base is built. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "LEGO Technic", "Mechanisms", "Diorama Design"],
    images: [
      { src: "assets/images/lambda-shuttle-landing/landing-1.jpg", caption: "Shuttle on the landing pad" },
      { src: "assets/images/lambda-shuttle-landing/landing-2.jpg", caption: "Wings raised, three-quarter view" },
      { src: "assets/images/lambda-shuttle-landing/landing-3.jpg", caption: "Jungle setting and water" },
      { src: "assets/images/lambda-shuttle-landing/landing-4.jpg", caption: "Close-up of the support frame" },
    ],
    references: [
      { src: "assets/images/lambda-shuttle-landing/reference-lambda.jpg", caption: "Reference: Lambda-class shuttle" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "at-at-walker",
    title: "AT-AT Walker",
    category: "lego",
    tags: ["lego", "star-wars", "vehicle", "moc"],
    summary:
      "A free-standing AT-AT walker with an opening troop bay, built to stand on four slender legs.",
    description: [
      "A LEGO AT-AT walker from The Empire Strikes Back. The body sits high on four jointed legs, and the roof panels lift off to show the troop compartment inside.",
      "Add your notes here: how you kept the legs stiff enough to carry the body, the scale, and part count. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Scale Modeling", "MOC Design"],
    images: [
      { src: "assets/images/at-at-walker/at-at-2.jpg", caption: "Side profile" },
      { src: "assets/images/at-at-walker/at-at-1.jpg", caption: "Three-quarter view" },
      { src: "assets/images/at-at-walker/at-at-3.jpg", caption: "Roof panel opened" },
      { src: "assets/images/at-at-walker/at-at-4.jpg", caption: "Troop bay interior" },
      { src: "assets/images/at-at-walker/at-at-5.jpg", caption: "Side view with the bay open" },
    ],
    references: [
      { src: "assets/images/at-at-walker/reference-at-at.jpg", caption: "Reference: AT-AT walker" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "imperial-star-destroyer",
    title: "Imperial Star Destroyer",
    category: "lego",
    tags: ["lego", "star-wars", "spacecraft", "moc"],
    summary:
      "An Imperial-class Star Destroyer on a display stand, plus a micro-scale version of the same ship.",
    description: [
      "A LEGO Imperial-class Star Destroyer mounted on an angled display stand, with the wedge hull, the command tower and the blue engine glow at the stern. A much smaller micro-scale version of the same ship is shown alongside it.",
      "Add your notes here: how you built the angled hull plates, how the stand attaches, and the size of each version. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Scale Modeling", "MOC Design"],
    images: [
      { src: "assets/images/imperial-star-destroyer/isd-1.jpg", caption: "On its display stand" },
      { src: "assets/images/imperial-star-destroyer/isd-2.jpg", caption: "Side view" },
      { src: "assets/images/imperial-star-destroyer/isd-3.jpg", caption: "Three-quarter view from above" },
      { src: "assets/images/imperial-star-destroyer/isd-4.jpg", caption: "Stern and engines" },
      { src: "assets/images/imperial-star-destroyer/isd-micro.jpg", caption: "Micro-scale version" },
    ],
    references: [
      { src: "assets/images/imperial-star-destroyer/reference-isd.jpg", caption: "Reference: Imperial-class Star Destroyer" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "star-wars-starfighters",
    title: "Star Wars Starfighters",
    category: "lego",
    tags: ["lego", "star-wars", "spacecraft", "mini-build", "moc"],
    summary:
      "A collection of small Star Wars ships: X-Wing, Y-Wing, U-Wing, A-Wing, TIE Fighter, Lambda shuttle and AT-ST, several on flight stands.",
    description: [
      "A set of small-scale Star Wars builds, most mounted on flight stands: an X-Wing, a blue Y-Wing, a U-Wing, an A-Wing, a TIE Fighter, a Lambda-class shuttle and an AT-ST walker, along with micro versions of the X-Wing, TIE Fighter and AT-ST.",
      "Add your notes here: which ones you designed from scratch, the scale you worked at, and the trickiest shape to capture. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Micro-Scale Design", "MOC Design"],
    images: [
      { src: "assets/images/star-wars-starfighters/x-wing-1.jpg", caption: "X-Wing on a flight stand" },
      { src: "assets/images/star-wars-starfighters/x-wing-2.jpg", caption: "X-Wing, front view" },
      { src: "assets/images/star-wars-starfighters/x-wing-micro.jpg", caption: "Micro X-Wing" },
      { src: "assets/images/star-wars-starfighters/y-wing-1.jpg", caption: "Y-Wing on a flight stand" },
      { src: "assets/images/star-wars-starfighters/y-wing-2.jpg", caption: "Y-Wing, rear view" },
      { src: "assets/images/star-wars-starfighters/y-wing-3.jpg", caption: "Y-Wing, top view" },
      { src: "assets/images/star-wars-starfighters/u-wing-1.jpg", caption: "U-Wing on a flight stand" },
      { src: "assets/images/star-wars-starfighters/u-wing-2.jpg", caption: "U-Wing, wings swept" },
      { src: "assets/images/star-wars-starfighters/u-wing-3.jpg", caption: "U-Wing, side view" },
      { src: "assets/images/star-wars-starfighters/a-wing.jpg", caption: "A-Wing" },
      { src: "assets/images/star-wars-starfighters/tie-1.jpg", caption: "TIE Fighter" },
      { src: "assets/images/star-wars-starfighters/tie-2.jpg", caption: "TIE Fighter, side view" },
      { src: "assets/images/star-wars-starfighters/tie-micro.jpg", caption: "Micro TIE Fighter" },
      { src: "assets/images/star-wars-starfighters/lambda-1.jpg", caption: "Lambda-class shuttle" },
      { src: "assets/images/star-wars-starfighters/lambda-2.jpg", caption: "Lambda shuttle, wings folded" },
      { src: "assets/images/star-wars-starfighters/at-st-1.jpg", caption: "AT-ST walker" },
      { src: "assets/images/star-wars-starfighters/at-st-micro.jpg", caption: "Micro AT-ST" },
    ],
    references: [
      { src: "assets/images/star-wars-starfighters/reference-x-wing.jpg", caption: "Reference: X-Wing" },
      { src: "assets/images/star-wars-starfighters/reference-y-wing.jpg", caption: "Reference: Y-Wing" },
      { src: "assets/images/star-wars-starfighters/reference-u-wing.jpg", caption: "Reference: U-Wing" },
      { src: "assets/images/star-wars-starfighters/reference-a-wing.jpg", caption: "Reference: A-Wing" },
      { src: "assets/images/star-wars-starfighters/reference-tie.jpg", caption: "Reference: TIE Fighter" },
      { src: "assets/images/star-wars-starfighters/reference-at-st.jpg", caption: "Reference: AT-ST" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "project-hail-mary",
    title: "Project Hail Mary Spacecraft",
    category: "lego",
    tags: ["lego", "spacecraft", "moc"],
    summary:
      "The Hail Mary from Andy Weir's novel, with its long spin tether and engine cluster, built on a display stand.",
    description: [
      "A LEGO model of the Hail Mary, the interstellar ship from Andy Weir's novel Project Hail Mary. The build has the cluster of white engine pods, the long tether boom and the solar panel arrays, mounted on a stand.",
      "Add your notes here: how you interpreted the ship from the book and film, how the tether is supported, and the size. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Scale Modeling", "MOC Design"],
    images: [
      { src: "assets/images/project-hail-mary/hail-mary-1.jpg", caption: "On its stand, full length with tether" },
      { src: "assets/images/project-hail-mary/hail-mary-2.jpg", caption: "Top view with solar arrays" },
      { src: "assets/images/project-hail-mary/hail-mary-3.jpg", caption: "Engine cluster" },
      { src: "assets/images/project-hail-mary/hail-mary-4.jpg", caption: "Three-quarter view" },
    ],
    references: [
      { src: "assets/images/project-hail-mary/reference-hail-mary.jpg", caption: "Reference: the Hail Mary" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "jurassic-park-jeep",
    title: "Jurassic Park Jeep",
    category: "lego",
    tags: ["lego", "vehicle", "moc"],
    summary:
      "The red-and-white Jurassic Park tour Jeep Wrangler, with an open roll cage and oversized off-road tires.",
    description: [
      "A LEGO version of the Jurassic Park tour Jeep Wrangler in its red-and-white park livery, with an open roll cage, a spare tire and chunky off-road wheels.",
      "Add your notes here: scale, whether the steering or suspension works, and how you got the livery. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Scale Modeling", "MOC Design"],
    images: [
      { src: "assets/images/jurassic-park-jeep/jeep-1.jpg", caption: "Three-quarter view" },
      { src: "assets/images/jurassic-park-jeep/jeep-2.jpg", caption: "Front view" },
      { src: "assets/images/jurassic-park-jeep/jeep-3.jpg", caption: "Rear view" },
    ],
    references: [
      { src: "assets/images/jurassic-park-jeep/reference-jeep.jpg", caption: "Reference: Jurassic Park Jeep Wrangler" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "rocket-league-cars",
    title: "Rocket League Octane and Fennec",
    category: "lego",
    tags: ["lego", "vehicle", "mini-build", "moc"],
    summary:
      "Two of the best-known cars from Rocket League, the Octane and the Fennec, built as a matched pair.",
    description: [
      "LEGO versions of the Octane and the Fennec, two of the most popular cars in the game Rocket League, built at the same scale so they can sit side by side.",
      "Add your notes here: how you captured each car's shape at this size and any features like the boost nozzle. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Micro-Scale Design", "MOC Design"],
    images: [
      { src: "assets/images/rocket-league-cars/cars-1.jpg", caption: "Octane and Fennec, three-quarter view" },
      { src: "assets/images/rocket-league-cars/cars-2.jpg", caption: "Side by side" },
      { src: "assets/images/rocket-league-cars/cars-3.jpg", caption: "Rear view" },
      { src: "assets/images/rocket-league-cars/cars-4.jpg", caption: "Top view" },
    ],
    references: [
      { src: "assets/images/rocket-league-cars/reference-rocket-league.jpg", caption: "Reference: Octane and Fennec" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "technic-mechanism",
    title: "LEGO Technic Motorized Mechanism",
    category: "lego",
    tags: ["lego", "technic", "moc"],
    summary:
      "A large motorized Technic build with a dense internal frame and gearing.",
    description: [
      "A large LEGO Technic build with a motor, a beam frame and gearing packed inside a red, white and black shell.",
      "Add your notes here: what this machine does, how it is powered and driven, and what you learned building it. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO Technic", "Gear Trains", "Motorization"],
    images: [
      { src: "assets/images/technic-mechanism/mechanism-1.jpg", caption: "Front view with motor" },
      { src: "assets/images/technic-mechanism/mechanism-2.jpg", caption: "Side view of the frame" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "technic-chassis",
    title: "LEGO Technic Car Chassis",
    category: "lego",
    tags: ["lego", "technic", "vehicle", "moc"],
    summary:
      "A bare Technic car chassis with independent suspension and large wheels, built to show the drivetrain and steering.",
    description: [
      "A LEGO Technic rolling chassis with no bodywork, so the suspension, steering and drivetrain are all visible.",
      "Add your notes here: which systems work (steering, suspension, differential), and what you were testing with this build. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO Technic", "Suspension Design", "Drivetrain"],
    images: [
      { src: "assets/images/technic-chassis/chassis-1.jpg", caption: "Three-quarter view" },
      { src: "assets/images/technic-chassis/chassis-2.jpg", caption: "Front suspension and steering" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "mini-aircraft",
    title: "Mini-Builds: Aircraft",
    category: "lego",
    tags: ["lego", "aircraft", "aviation", "mini-build", "moc"],
    summary:
      "Small-scale planes: two WWII carrier fighters, a red propeller plane on a stand, an airliner and a grey jet.",
    description: [
      "A run of small aircraft builds: two WWII-era propeller fighters (with a Dauntless and an F4U Corsair as references), a red propeller plane on a display stand, a white airliner and a grey jet.",
      "Add your notes here: which aircraft each one is meant to be and how you captured each shape at this scale. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Micro-Scale Design", "Aviation"],
    images: [
      { src: "assets/images/mini-aircraft/fighter-dark-1.jpg", caption: "Dark grey WWII fighter" },
      { src: "assets/images/mini-aircraft/fighter-grey-1.jpg", caption: "Grey WWII fighter" },
      { src: "assets/images/mini-aircraft/fighter-grey-2.jpg", caption: "Grey WWII fighter, top view" },
      { src: "assets/images/mini-aircraft/red-prop.jpg", caption: "Red propeller plane on a stand" },
      { src: "assets/images/mini-aircraft/airliner-1.jpg", caption: "Airliner" },
      { src: "assets/images/mini-aircraft/airliner-2.jpg", caption: "Airliner, front view" },
      { src: "assets/images/mini-aircraft/grey-plane.jpg", caption: "Grey jet" },
    ],
    references: [
      { src: "assets/images/mini-aircraft/reference-dauntless.jpg", caption: "Reference: Dauntless" },
      { src: "assets/images/mini-aircraft/reference-corsair.jpg", caption: "Reference: F4U Corsair" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "mini-vehicles",
    title: "Mini-Builds: Vehicles",
    category: "lego",
    tags: ["lego", "vehicle", "mini-build", "moc"],
    summary:
      "Small-scale vehicles: a yellow semi truck and trailer, a white rover, a red race car and more.",
    description: [
      "A run of small vehicle builds: a yellow semi truck with a grey trailer, a white-and-red off-road rover, a small red race car, and a black build.",
      "Add your notes here: what each one is and anything clever about how it's built. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Micro-Scale Design", "Parts Efficiency"],
    images: [
      { src: "assets/images/mini-vehicles/semi-1.jpg", caption: "Semi truck and trailer" },
      { src: "assets/images/mini-vehicles/semi-2.jpg", caption: "Semi truck, front view" },
      { src: "assets/images/mini-vehicles/rover-1.jpg", caption: "Off-road rover" },
      { src: "assets/images/mini-vehicles/rover-2.jpg", caption: "Rover, rear view" },
      { src: "assets/images/mini-vehicles/race-car-1.jpg", caption: "Red race car" },
      { src: "assets/images/mini-vehicles/race-car-2.jpg", caption: "Race car, top view" },
      { src: "assets/images/mini-vehicles/black-build.jpg", caption: "Black build (add a name)" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "mini-architecture-games",
    title: "Mini-Builds: Stadium, Courtyard and Chess Set",
    category: "lego",
    tags: ["lego", "mini-build", "moc"],
    summary:
      "A red-and-blue soccer stadium, a walled courtyard with towers, and a playable brick-built chess set.",
    description: [
      "Three small builds that aren't vehicles: a soccer stadium in red and blue with a green pitch inside, a walled courtyard with white spires at the corners, and a full chess set with board and pieces.",
      "Add your notes here: which stadium it is, what the courtyard represents, and whether the chess set is playable. (This description is a placeholder for you to edit.)",
    ],
    tools: ["LEGO", "Micro-Scale Design", "Parts Efficiency"],
    images: [
      { src: "assets/images/mini-architecture-games/stadium-1.jpg", caption: "Soccer stadium" },
      { src: "assets/images/mini-architecture-games/stadium-2.jpg", caption: "Stadium, view into the pitch" },
      { src: "assets/images/mini-architecture-games/stadium-3.jpg", caption: "Stadium from above" },
      { src: "assets/images/mini-architecture-games/courtyard-1.jpg", caption: "Walled courtyard" },
      { src: "assets/images/mini-architecture-games/courtyard-2.jpg", caption: "Courtyard, side view" },
      { src: "assets/images/mini-architecture-games/chess-1.jpg", caption: "Chess set" },
      { src: "assets/images/mini-architecture-games/chess-2.jpg", caption: "Chess set, three-quarter view" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "wind-turbine-competition",
    title: "Competition Wind Turbine",
    category: "competition",
    tags: ["cad", "fabrication", "moc"],
    date: "2026 — In Progress",
    summary:
      "Designing and manufacturing a functioning wind turbine for competition at Northeastern, with a focus on blade shape, pitch control, and an emergency brake.",
    description: [
      "Ongoing project with Renewable Energy Northeastern University: designing and building a functioning wind turbine for competition.",
      "Working in Onshape to design the blade shape, a pitch-control mechanism for the blades, and an emergency brake system — covering aerodynamic, mechanical, and safety-critical design in one build.",
    ],
    tools: ["Onshape", "CAD", "Mechanical Design"],
    images: [],
    links: {},
    featured: true,
    needsDetail: true,
  },
  {
    slug: "frc-robot-design",
    title: "FIRST Robotics Competition — Robot Subsystems",
    category: "competition",
    tags: ["cad", "robotics"],
    date: "2022 — 2025",
    summary:
      "Four seasons modeling and designing subsystems for a partially autonomous competition robot in Onshape.",
    description: [
      "Four years on a FIRST Robotics Competition (FRC) team, modeling robot parts and subsystems in Onshape and designing solutions to the season's game challenges on a partially autonomous robot.",
      "Add specifics here — which subsystems you owned (drivetrain, intake, climber, etc.), the team number, competition results, and a photo or CAD render if you have one.",
    ],
    tools: ["Onshape", "CAD", "Robotics"],
    images: [],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "gesture-recognition-active-suspension",
    title: "Gesture Recognition for Active Suspension",
    category: "research",
    tags: ["research", "cad"],
    date: "Apr — May 2025",
    summary:
      "Trained a machine-learning model to recognize hand, face, and body gestures, then used it to drive a car's active suspension in response — a patented result from a Clearmotion internship.",
    description: [
      "During an internship at Clearmotion, trained and coordinated a machine-learning model to recognize various hand, face, and body gestures from hundreds of collected data samples.",
      "The resulting model was patented and functional: it could program a car to respond to gestures in real time — for example, waving at the car would make it wave back, using Clearmotion's active suspension technology.",
    ],
    tools: ["Machine Learning", "Python", "Active Suspension Systems"],
    images: [],
    links: {},
    featured: true,
    needsDetail: false,
  },
  {
    slug: "lufthansa-747",
    title: "Lufthansa 747 Wall Lamp",
    category: "personal",
    tags: ["aircraft", "aviation", "fabrication"],
    summary:
      "A Lufthansa Boeing 747 model that mounts on the wall and lights up as a room lamp.",
    description: [
      "A white Boeing 747 model in Lufthansa livery that hangs on the wall and glows as a lamp, with the power cable running down from the tail.",
      "Add your notes here: how it was made (printed, kit, or modified), how the lighting is wired, and the size. (This description is a placeholder for you to edit.)",
    ],
    tools: ["Fabrication", "Lighting", "Aviation"],
    images: [
      { src: "assets/images/lufthansa-747/747-1.jpg", caption: "Lufthansa 747, side view" },
      { src: "assets/images/lufthansa-747/747-2.jpg", caption: "Front view" },
      { src: "assets/images/lufthansa-747/747-3.jpg", caption: "Top view" },
      { src: "assets/images/lufthansa-747/747-lamp-1.jpg", caption: "Mounted on the wall" },
      { src: "assets/images/lufthansa-747/747-lamp-2.jpg", caption: "Lit up as a lamp" },
      { src: "assets/images/lufthansa-747/747-lamp-3.jpg", caption: "In the room" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
  {
    slug: "poker-chip-case",
    title: "Laser-Cut Poker Chip Case",
    category: "fabrication",
    tags: ["fabrication", "woodworking", "moc"],
    summary:
      "A laser-cut plywood case with finger joints and a hinged lid, holding a set of engraved wooden poker chips and a deck of cards.",
    description: [
      "A plywood box cut on a laser cutter, assembled with finger joints and a hinged lid. Inside are five rows of wooden poker chips, each engraved with a different pattern, and a slot for a deck of cards.",
      "Add your notes here: what software you designed it in, the material thickness, how you sized the chip rows, and how many chips it holds. (This description is a placeholder for you to edit.)",
    ],
    tools: ["Laser Cutting", "CAD", "Woodworking"],
    images: [
      { src: "assets/images/poker-chip-case/case-1.jpg", caption: "Open, with sample chips in front" },
      { src: "assets/images/poker-chip-case/case-2.jpg", caption: "Chip rows and card slot" },
      { src: "assets/images/poker-chip-case/case-3.jpg", caption: "Closed case" },
    ],
    links: {},
    featured: false,
    needsDetail: true,
  },
];
